-- ============================================================================
-- ARCHIVED - do not run this.
-- ============================================================================
-- The Supabase project was deleted on 2026-09-30, after the delta sync. The
-- instructions below told someone to run UPDATE statements in the Supabase SQL
-- Editor, and that is exactly what makes this file dangerous: the project is
-- gone, but these statements would still run correctly against a Postgres that
-- happens to be reachable, including the production database.
--
-- These changes are already applied. `migrate.sh` step 4 performs them in the
-- TARGET as part of the migration, and the counts below were confirmed at the
-- time:
--
--   53 rows   status        'Input' -> 'Leads'
--    2 rows   interest_level 'Low'   -> '-'
--
-- Leaving executable SQL in docs/ invites someone to run it against whatever
-- database they are currently pointed at. Keeping it as a comment block means
-- the reasoning survives without the trigger.
--
-- Original instructions, preserved for the record only:
--
--   Step 1 - BACKUP (read-only)
--     SELECT id, brand_name, status AS status_sekular
--     FROM public.leads WHERE status = 'Input' ORDER BY brand_name;
--
--   Step 2 - NORMALISE
--     'Input' and 'Leads' mean the same thing: the brand is in the database but
--     nobody has contacted it. 'Chated' means the first contact happened.
--
--     UPDATE public.leads SET status = 'Leads' WHERE status = 'Input';
--
--     'Low' is not a valid interest level. The valid set is HOT / WARM / COLD /
--     '-', and 'Low' was written by an import that used the task *priority*
--     vocabulary by mistake. Two rows, no usable signal, so they become unset.
--
--     UPDATE public.leads SET interest_level = '-' WHERE interest_level = 'Low';
--
--   Step 3 - VERIFY (read-only)
--     SELECT status, count(*) FROM public.leads
--      WHERE status NOT IN ('Leads','Chated','Responsed','Set Meeting','Hold',
--                           'Close Win','Close Lost','Failed') GROUP BY status;
--     -- expect 0 rows
--
--     SELECT interest_level, count(*) FROM public.leads
--      WHERE interest_level NOT IN ('HOT','WARM','COLD','-') GROUP BY interest_level;
--     -- expect 0 rows
-- ============================================================================
